name: alphaRelease

on:
  pull_request:
    branches: [ develop ]

jobs:
  SolarTeslaCharger:
    name: Building SolarTeslaCharger image
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup dotnet
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '6.0.x'
    
    - name: Run unit tests
      run: dotnet test SolarTeslaCharger.Tests

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1

    - name: Buildx
      id: buildx
      uses: docker/setup-buildx-action@v1

    - name: DockerHub login
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASS}}

    - name: Build and push SolarTeslaCharger
      uses: docker/build-push-action@v2
      with:
        file: ./SolarTeslaCharger/Server/Dockerfile
        platforms: linux/amd64,linux/arm64,linux/arm/v7
        push: true
        tags: pkuehnel/solarteslacharger:alpha

  SmaEnergymeterPlugin:
    name: Building SMAPlugin Image
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1

    - name: Buildx
      id: buildx
      uses: docker/setup-buildx-action@v1

    - name: DockerHub login
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASS}}

    - name: Build and push SmaPlugin
      uses: docker/build-push-action@v2
      with:
        file: ./Plugins.SmaEnergymeter/Dockerfile
        platforms: linux/amd64,linux/arm64,linux/arm/v7
        push: true
        tags: pkuehnel/solarteslachargersmaplugin:alpha

  SolarEdgePlugin:
    name: Building SolarEdgePlugin Image
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1

    - name: Buildx
      id: buildx
      uses: docker/setup-buildx-action@v1

    - name: DockerHub login
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASS}}

    - name: Build and push SolarEdgePlugin
      uses: docker/build-push-action@v2
      with:
        file: ./Plugins.SolarEdge/Dockerfile
        platforms: linux/amd64,linux/arm64,linux/arm/v7
        push: true
        tags: pkuehnel/solarteslachargersolaredgeplugin:alpha
