name: Autoremove Waiting for feedback
on:
  issue_comment:
    types:
      - created
jobs:
  label_issues:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - uses: andymckay/labeler@master
        with:
          remove-labels: "waiting for feedback"
          repo-token: ${{ secrets.GITHUB_TOKEN }}
