name: Release

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  TeslaSolarCharger:
    name: Building TeslaSolarCharger image
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1

    - name: Setup dotnet
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '6.0.x'
    
    - name: Run unit tests
      run: dotnet test TeslaSolarCharger.Tests
      
    - name: Buildx
      id: buildx
      uses: docker/setup-buildx-action@v1

    - name: DockerHub login
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASS}}
        
    - name: Build and push TeslaSolarCharger
      uses: docker/build-push-action@v2
      with:
        file: ./TeslaSolarCharger/Server/Dockerfile
        platforms: linux/amd64,linux/arm64,linux/arm/v7
        push: true
        tags: pkuehnel/teslasolarcharger:edge

  SmaEnergymeterPlugin:
    name: Building SMAPlugin Image
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1

    - name: Buildx
      id: buildx
      uses: docker/setup-buildx-action@v1

    - name: DockerHub login
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASS}}
        
    - name: Build and push SmaPlugin
      uses: docker/build-push-action@v2
      with:
        file: ./Plugins.SmaEnergymeter/Dockerfile
        platforms: linux/amd64,linux/arm64,linux/arm/v7
        push: true
        tags: pkuehnel/teslasolarchargersmaplugin:edge

  SolarEdgePlugin:
    name: Building SolarEdgePlugin Image
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1

    - name: Buildx
      id: buildx
      uses: docker/setup-buildx-action@v1

    - name: DockerHub login
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASS}}

    - name: Build and push SolarEdgePlugin
      uses: docker/build-push-action@v2
      with:
        file: ./Plugins.SolarEdge/Dockerfile
        platforms: linux/amd64,linux/arm64,linux/arm/v7
        push: true
        tags: pkuehnel/teslasolarchargersolaredgeplugin:edge
