name: Release

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Building image
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Buildx
      id: buildx
      uses: docker/setup-buildx-action@v1

    - name: Build and push SmartTeslaAmpSetter
      uses: docker/build-push-action@v2
      with:
        file: ./SmartTeslaAmpSetter/Dockerfile
        platforms: linux/amd64,linux/arm64
        push: true
        tags: pkuehnel/smartteslaampsetter:latest

    - name: Build and push SmaPlugin
      uses: docker/build-push-action@v2
      with:
        file: ./Plugins.SmaEnergymeter/Dockerfile
        platforms: linux/amd64,linux/arm64
        push: true
        tags: pkuehnel/smartteslaampsettersmaplugin:latest
