name: versionRelease
on:
  release:
    types: [published]

jobs:
  releaseFiles:
    name: Release
    strategy:
      matrix:
        kind: ['linux-x64', 'linux-arm64', 'linux-arm']
        include:
          - kind: linux-x64
            os: ubuntu-latest
            target: linux-x64
          - kind: linux-arm64
            os: ubuntu-latest
            target: linux-arm64
          - kind: linux-arm
            os: ubuntu-latest
            target: linux/arm/v7
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Setup dotnet
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '6.0.x'
    
      - name: Run unit tests
        run: dotnet test TeslaSolarCharger.Tests

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Setup dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x

      - name: Build TeslaSolarCharger
        shell: bash
        run: |
          # Define some variables for things we need
          tag=$(git describe --tags --abbrev=0)
          release_name="TeslaSolarCharger-$tag-${{ matrix.kind }}"

          # Build everything
          dotnet publish TeslaSolarCharger/Server/TeslaSolarCharger.Server.csproj --runtime "${{ matrix.kind }}" -c Release -o "$release_name"

          # Pack files
          tar czvf "${release_name}.tar.gz" "$release_name"

          # Delete output directory
          rm -r "$release_name"
      
      - name: Build Plugins.SmaEnergymeter
        shell: bash
        run: |
          # Define some variables for things we need
          tag=$(git describe --tags --abbrev=0)
          release_name="Plugins.SmaEnergymeter-$tag-${{ matrix.kind }}"

          # Build everything
          dotnet publish Plugins.SmaEnergymeter/Plugins.SmaEnergymeter.csproj --runtime "${{ matrix.kind }}" -c Release -o "$release_name"

          # Pack files
          tar czvf "${release_name}.tar.gz" "$release_name"

          # Delete output directory
          rm -r "$release_name"

      - name: Build Plugins.SolarEdge
        shell: bash
        run: |
          # Define some variables for things we need
          tag=$(git describe --tags --abbrev=0)
          release_name="Plugins.SolarEdge-$tag-${{ matrix.kind }}"

          # Build everything
          dotnet publish Plugins.SolarEdge/Plugins.SolarEdge.csproj --runtime "${{ matrix.kind }}" -c Release -o "$release_name"

          # Pack files
          tar czvf "${release_name}.tar.gz" "$release_name"

          # Delete output directory
          rm -r "$release_name"

      - name: Publish
        uses: softprops/action-gh-release@v1
        with:
          files: "*.tar.gz"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  releaseDockerLatestTeslaSolarCharger:
    name: Building TeslaSolarCharger image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          # list of Docker images to use as base name for tags
          images: |
            pkuehnel/teslasolarcharger
          # generate Docker tags based on the following events/attributes
          tags: |
            type=semver,pattern={{version}}
      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      
      - name: Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      
      - name: DockerHub login
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASS}}
          
      - name: Build and push TeslaSolarCharger
        uses: docker/build-push-action@v2
        with:
          file: ./TeslaSolarCharger/Server/Dockerfile
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          push: true
          tags: ${{ steps.meta.outputs.tags }}

  releaseDockerLatestSmartTeslaAmpSetter:
    name: Building SmartTeslaAmpSetter image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          # list of Docker images to use as base name for tags
          images: |
            pkuehnel/smartteslaampsetter
          # generate Docker tags based on the following events/attributes
          tags: |
            type=semver,pattern={{version}}
      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      
      - name: Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      
      - name: DockerHub login
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASS}}
          
      - name: Build and push SmartTeslaAmpSetter
        uses: docker/build-push-action@v2
        with:
          file: ./TeslaSolarCharger/Server/Dockerfile
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          push: true
          tags: ${{ steps.meta.outputs.tags }}

  releaseDockerLatestSmaEnergymeterpluginTeslaSolarCharger:
    name: Building SMAPlugin Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          # list of Docker images to use as base name for tags
          images: |
            pkuehnel/teslasolarchargersmaplugin
          # generate Docker tags based on the following events/attributes
          tags: |
            type=semver,pattern={{version}}
      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      
      - name: Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      
      - name: DockerHub login
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASS}}
          
      - name: Build and push SmaPlugin
        uses: docker/build-push-action@v2
        with:
          file: ./Plugins.SmaEnergymeter/Dockerfile
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          push: true
          tags: ${{ steps.meta.outputs.tags }}

  releaseDockerLatestSmaEnergymeterpluginSmartTeslaAmpSetter:
    name: Building SMAPlugin Image old name
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          # list of Docker images to use as base name for tags
          images: |
            pkuehnel/smartteslaampsettersmaplugin
          # generate Docker tags based on the following events/attributes
          tags: |
            type=semver,pattern={{version}}
      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      
      - name: Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      
      - name: DockerHub login
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASS}}
          
      - name: Build and push SmaPlugin
        uses: docker/build-push-action@v2
        with:
          file: ./Plugins.SmaEnergymeter/Dockerfile
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          push: true
          tags: ${{ steps.meta.outputs.tags }}

  releaseDockerLatestSolarEdgepluginTeslaSolarCharger:
    name: Building SolarEdgePlugin Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          # list of Docker images to use as base name for tags
          images: |
            pkuehnel/teslasolarchargersolaredgeplugin
          # generate Docker tags based on the following events/attributes
          tags: |
            type=semver,pattern={{version}}
      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      
      - name: Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      
      - name: DockerHub login
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASS}}
          
      - name: Build and push SolarEdgePlugin
        uses: docker/build-push-action@v2
        with:
          file: ./Plugins.SolarEdge/Dockerfile
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          push: true
          tags: ${{ steps.meta.outputs.tags }}

  releaseDockerLatestSolarEdgepluginSmartTeslaAmpSetter:
    name: Building SolarEdgePlugin Image old name
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          # list of Docker images to use as base name for tags
          images: |
            pkuehnel/smartteslaampsettersolaredgeplugin
          # generate Docker tags based on the following events/attributes
          tags: |
            type=semver,pattern={{version}}
      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      
      - name: Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      
      - name: DockerHub login
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASS}}
          
      - name: Build and push SolarEdgePlugin
        uses: docker/build-push-action@v2
        with:
          file: ./Plugins.SolarEdge/Dockerfile
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          push: true
          tags: ${{ steps.meta.outputs.tags }}